project_id = "wzylualqefqufphwsaql"

[functions.create-user]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false

[functions.expire-trials]
verify_jwt = false

[functions.create-razorpay-subscription]
verify_jwt = false
